language: node_js
node_js:
  - "node"
after_success:
  - mkdir www
  - mustache src/data.json src/index.mustache > www/index.html
  - cp src/404.html www
  - cp -r src/js www
  - cp -r src/img www
  - mkdir www/burger
  - cp src/burger.html www/burger/index.html
  - cp src/meta/.surgeignore www
  - cp src/meta/CNAME www
  - mkdir www/css
  - sass src/sass/style.scss > www/css/style.css
  - sass src/sass/bin4features.scss > www/css/bin4features.css
  - surge www
