language: node_js
node_js:
  - "0.12"
after_success:
  - cp -r /home/travis/build/connor-bracewell/nnorco/src /home/travis/build/connor-bracewell/nnorco/www
  - mkdir /home/travis/build/connor-bracewell/nnorco/www/css
  - sass /home/travis/build/connor-bracewell/nnorco/www/sass/style.scss > /home/travis/build/connor-bracewell/nnorco/www/css/style.css
  - sass /home/travis/build/connor-bracewell/nnorco/www/sass/bin4features.scss > /home/travis/build/connor-bracewell/nnorco/www/css/bin4features.css
  - rm -r /home/travis/build/connor-bracewell/nnorco/www/sass
  - surge /home/travis/build/connor-bracewell/nnorco/www
