language: node_js
node_js:
  - "node"
after_success:
  - mkdir www
  - mustache src/data.json src/index.mustache > www/index.html
  - cp src/404.html www
  - mkdir www/js
  - tsc --outFile www/js/main.js src/ts/main.ts
  - cp -r src/js/* www/js
  - cp -r src/img www
  - mkdir www/burger
  - cp src/burger.html www/burger/index.html
  - mkdir www/css
  - sass src/sass/style.scss > www/css/style.css
  - sass src/sass/bin4features.scss > www/css/bin4features.css
  - |
      if [ "$TRAVIS_BRANCH" = "master" ]; then
        surge www https://nnor.co
      elif [ "$TRAVIS_BRANCH" = "dev" ]; then
        surge www https://dev.nnor.co
        surge www nnorco.surge.sh
      fi
