language: node_js
node_js:
  - "node"
after_success:
  - mkdir www
  - curl -H 'User-Agent: connor-bracewell' https://api.github.com/repos/connor-bracewell/nnorco/commits > src/commit.json
  - cat src/commit.json
  - cat src/data.json
  - jq ".commit_date=\"$(date "+%m/%Y")\"" src/data.json > src/data2.json
  - cat src/data2.json
  - jq ".commit_hash=$(cat src/commit.json | jq .[0].sha[0:7])" src/data2.json > src/data3.json
  - cat src/data3.json
  - jq ".commit_url=$(cat src/commit.json | jq .[0].html_url)" src/data3.json > src/data4.json
  - cat src/data4.json
  - mustache src/data4.json src/index.mustache > www/index.html
  - cp src/404.html www
  - mkdir www/js
  - tsc --outFile www/js/main.js src/ts/main.ts
  - cp -r src/js/* www/js
  - cp -r src/img www
  - mkdir www/burger
  - cp src/burger.html www/burger/index.html
  - mkdir www/css
  - sass src/sass/style.scss > www/css/style.css
  - sass src/sass/bin4features.scss > www/css/bin4features.css
  - |
      if [ "$TRAVIS_BRANCH" = "master" ]; then
        surge www https://nnor.co
      elif [ "$TRAVIS_BRANCH" = "dev" ]; then
        surge www https://dev.nnor.co
        surge www nnorco.surge.sh
      fi
